name: myenv_app
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.2
  - altair=4.2.0
  - appnope=0.1.3
  - argh=0.26.2
  - arrow-cpp=5.0.0
  - astor=0.8.1
  - attrs=21.4.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - base58=2.1.1
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=5.0.0
  - boto3=1.22.4
  - botocore=1.25.4
  - bottleneck=1.3.4
  - branca=0.5.0
  - brotli=1.0.7
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.3.29
  - cachetools=5.0.0
  - certifi=2021.10.8
  - charset-normalizer=2.0.12
  - cryptography=35.0.0
  - cycler=0.11.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - folium=0.12.1.post1
  - fonttools=4.25.0
  - freetype=2.11.0
  - gflags=2.2.2
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glog=0.5.0
  - grpc-cpp=1.40.0
  - idna=3.3
  - importlib_resources=5.7.1
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jinja2=3.1.1
  - jmespath=1.0.0
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter_client=7.1.2
  - jupyter_core=4.9.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.1.0
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=2.2.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.79.1
  - libcxx=12.0.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.1.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.18.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.3.0
  - libutf8proc=2.7.0
  - libwebp-base=1.2.2
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclient=0.6.0
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.11
  - numexpr=2.8.1
  - numpy-base=1.21.5
  - olefile=0.46
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1n
  - orc=1.7.0
  - packaging=21.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pydeck=0.7.1
  - pygments=2.12.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.8
  - pyyaml=6.0
  - pyzmq=22.3.0
  - re2=2021.09.01
  - readline=8.1.2
  - requests=2.27.1
  - s3transfer=0.5.2
  - semver=2.13.0
  - send2trash=1.8.0
  - setuptools=61.2.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.38.2
  - streamlit=1.8.1
  - streamlit-folium=0.6.7
  - tinycss2=1.1.1
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=4.2.0
  - urllib3=1.26.9
  - validators=0.18.2
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xlrd=2.0.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.0
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - backports-zoneinfo==0.2.1
    - blinker==1.4
    - cffi==1.15.0
    - click==8.0.4
    - debugpy==1.6.0
    - executing==0.8.3
    - importlib-metadata==4.11.3
    - ipykernel==6.13.0
    - ipython==8.2.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jupyter-client==7.3.0
    - jupyter-core==4.10.0
    - markupsafe==2.1.1
    - numpy==1.22.3
    - pandas==1.4.2
    - pillow==9.1.0
    - protobuf==3.20.1
    - psutil==5.9.0
    - pure-eval==0.2.2
    - pyarrow==7.0.0
    - pympler==1.0.1
    - pyparsing==3.0.8
    - pyrsistent==0.18.1
    - pytz==2022.1
    - pytz-deprecation-shim==0.1.0.post0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - stack-data==0.2.0
    - terminado==0.13.3
    - tzdata==2022.1
    - tzlocal==4.2
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
